name: Deployment
on: 
  push:
    branches:
      - main
jobs: 
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - uses: actions/checkout@v2

      - name: Install Pulumi Dependencies
        run: npm install
        working-directory: infra

      - name: Provision Infrastructure
        uses: pulumi/actions@v3
        with:
          command: up
          stack-name: dev
          work-dir: infra
        env:
          PULUMI_ACCESS_TOKEN: ${{secrets.PULUMI_ACCESS_TOKEN}}

